"""Native Python bindings for embedded BriskDB and optional listeners."""

from ._briskdb import (
    BriskDBError,
    BusyError,
    CancelledError,
    CancellationToken,
    CheckViolationError,
    Config,
    ConstraintViolationError,
    Cursor,
    DataCorruptionError,
    DataError,
    Database,
    DeadlineExceededError,
    FailedPreconditionError,
    ForeignKeyViolationError,
    IdempotencyConflictError,
    IntegrityError,
    InternalError,
    InvalidArgumentError,
    InvalidQueryError,
    InvalidTextEncodingError,
    LimitExceededError,
    NotNullViolationError,
    NumericOutOfRangeError,
    OperationalError,
    OutOfMemoryError,
    PermissionDeniedError,
    ProgrammingError,
    ReadOnlyError,
    Server,
    Session,
    Transaction,
    ShuttingDownError,
    StorageFullError,
    StorageUnavailableError,
    TypeMismatchError,
    UniqueViolationError,
    UnsupportedError,
    __version__,
    open,
)
from .api import (
    AsyncCursor,
    AsyncDatabase,
    AsyncServer,
    AsyncSession,
    AsyncTransaction,
    connect,
    connect_async,
    open_async,
)
from .remote import RemoteAttachment, attach_remote
from .patching import MongoPatch, patch

ASCENDING = 1
DESCENDING = -1


def __getattr__(name):
    if name in {"MongoClient", "AsyncMongoClient", "ReturnDocument", "IndexModel", "errors"}:
        from . import mongo
        return getattr(mongo, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

__all__ = [
    "MongoPatch",
    "patch",
    "ASCENDING",
    "DESCENDING",
    "RemoteAttachment",
    "attach_remote",
    "BriskDBError",
    "BusyError",
    "CancelledError",
    "CancellationToken",
    "CheckViolationError",
    "Config",
    "ConstraintViolationError",
    "Cursor",
    "DataCorruptionError",
    "DataError",
    "Database",
    "DeadlineExceededError",
    "FailedPreconditionError",
    "ForeignKeyViolationError",
    "IdempotencyConflictError",
    "IntegrityError",
    "InternalError",
    "InvalidArgumentError",
    "InvalidQueryError",
    "InvalidTextEncodingError",
    "LimitExceededError",
    "NotNullViolationError",
    "NumericOutOfRangeError",
    "OperationalError",
    "OutOfMemoryError",
    "PermissionDeniedError",
    "ProgrammingError",
    "ReadOnlyError",
    "Server",
    "Session",
    "Transaction",
    "ShuttingDownError",
    "StorageFullError",
    "StorageUnavailableError",
    "TypeMismatchError",
    "UniqueViolationError",
    "UnsupportedError",
    "AsyncCursor",
    "AsyncDatabase",
    "AsyncServer",
    "AsyncSession",
    "AsyncTransaction",
    "__version__",
    "connect",
    "connect_async",
    "open_async",
    "open",
]
