from typing import Any, Mapping, TypeVar
from pymongo.synchronous.collection import Collection as _Collection
from pymongo.synchronous.database import Database as _Database
from pymongo.asynchronous.collection import AsyncCollection as _AsyncCollection
from pymongo.asynchronous.database import AsyncDatabase as _AsyncDatabase

class IndexCompatibilityWarning(UserWarning): ...

_Document = TypeVar("_Document", bound=Mapping[str, Any])

class Collection(_Collection[_Document]):
    def __getitem__(self, name: str) -> Collection[_Document]: ...
    def __getattr__(self, name: str) -> Collection[_Document]: ...
    def with_options(self, *args: Any, **kwargs: Any) -> Collection[Any]: ...
    def create_indexes(self, indexes: Any, session: Any = ..., comment: Any = ...,
                       **kwargs: Any) -> list[str]: ...

class AsyncCollection(_AsyncCollection[_Document]):
    def __getitem__(self, name: str) -> AsyncCollection[_Document]: ...
    def __getattr__(self, name: str) -> AsyncCollection[_Document]: ...
    def with_options(self, *args: Any, **kwargs: Any) -> AsyncCollection[Any]: ...
    async def create_indexes(self, indexes: Any, session: Any = ..., comment: Any = ...,
                             **kwargs: Any) -> list[str]: ...

class Database(_Database[_Document]):
    def __getitem__(self, name: str) -> Collection[_Document]: ...
    def __getattr__(self, name: str) -> Collection[_Document]: ...
    def get_collection(self, *args: Any, **kwargs: Any) -> Collection[_Document]: ...
    def with_options(self, *args: Any, **kwargs: Any) -> Database[Any]: ...
    def create_collection(self, *args: Any, **kwargs: Any) -> Collection[_Document]: ...

class AsyncDatabase(_AsyncDatabase[_Document]):
    def __getitem__(self, name: str) -> AsyncCollection[_Document]: ...
    def __getattr__(self, name: str) -> AsyncCollection[_Document]: ...
    def get_collection(self, *args: Any, **kwargs: Any) -> AsyncCollection[_Document]: ...
    def with_options(self, *args: Any, **kwargs: Any) -> AsyncDatabase[Any]: ...
    async def create_collection(self, *args: Any, **kwargs: Any) -> AsyncCollection[_Document]: ...
