from pathlib import Path
from typing import Any, Optional
from ._briskdb import ContentionPolicy
from ._mongo_collections import (
    Database, AsyncDatabase, IndexCompatibilityWarning as IndexCompatibilityWarning,
)
from pymongo import (
    MongoClient as _MongoClient,
    AsyncMongoClient as _AsyncMongoClient,
    ASCENDING as ASCENDING,
    DESCENDING as DESCENDING,
    ReturnDocument as ReturnDocument,
    IndexModel as IndexModel,
    errors as errors,
)

class MongoClient(_MongoClient[dict[str, Any]]):
    def __enter__(self) -> MongoClient: ...
    def __getitem__(self, name: str) -> Database[dict[str, Any]]: ...
    def __getattr__(self, name: str) -> Database[dict[str, Any]]: ...
    def get_database(self, *args: Any, **kwargs: Any) -> Database[dict[str, Any]]: ...
    def get_default_database(self, *args: Any, **kwargs: Any) -> Database[dict[str, Any]]: ...
    def __init__(self, host: Any = ..., port: Any = ..., document_class: Any = ...,
                 tz_aware: Any = ..., connect: Any = ..., type_registry: Any = ...,
                 *, folder: Any = ..., shards: Optional[int] = ...,
                 contention_policy: Optional[ContentionPolicy] = ...,
                 index_build_timeout_ms: Optional[int] = ..., **kwargs: Any) -> None: ...
    @property
    def briskdb_path(self) -> Path: ...
    @property
    def briskdb_contention_policy(self) -> Optional[ContentionPolicy]: ...
    @property
    def briskdb_index_build_timeout_ms(self) -> int: ...

class AsyncMongoClient(_AsyncMongoClient[dict[str, Any]]):
    async def __aenter__(self) -> AsyncMongoClient: ...
    def __getitem__(self, name: str) -> AsyncDatabase[dict[str, Any]]: ...
    def __getattr__(self, name: str) -> AsyncDatabase[dict[str, Any]]: ...
    def get_database(self, *args: Any, **kwargs: Any) -> AsyncDatabase[dict[str, Any]]: ...
    def get_default_database(self, *args: Any, **kwargs: Any) -> AsyncDatabase[dict[str, Any]]: ...
    def __init__(self, host: Any = ..., port: Any = ..., document_class: Any = ...,
                 tz_aware: Any = ..., connect: Any = ..., type_registry: Any = ...,
                 *, folder: Any = ..., shards: Optional[int] = ...,
                 contention_policy: Optional[ContentionPolicy] = ...,
                 index_build_timeout_ms: Optional[int] = ..., **kwargs: Any) -> None: ...
    @property
    def briskdb_path(self) -> Path: ...
    @property
    def briskdb_contention_policy(self) -> Optional[ContentionPolicy]: ...
    @property
    def briskdb_index_build_timeout_ms(self) -> int: ...
