from contextlib import ContextDecorator
from os import PathLike
from typing import Any, Optional, Union
from .mongo import MongoClient

class MongoPatch(ContextDecorator):
    def __init__(self, folder: Optional[Union[str, PathLike[str]]] = ..., backend: str = ...,
                 *, shards: Optional[int] = ...) -> None: ...
    def __enter__(self) -> type[MongoClient]: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool: ...
    async def __aenter__(self) -> type[MongoClient]: ...
    async def __aexit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool: ...

def patch(folder: Optional[Union[str, PathLike[str]]] = ..., backend: str = ...,
          *, shards: Optional[int] = ...) -> MongoPatch: ...
