from os import PathLike
from typing import Any, Iterable, Mapping, Optional, Sequence, Union

class OpenOptions:
    @property
    def parquet_pruning(self) -> bool: ...
    @property
    def read_only(self) -> bool: ...
    def __init__(self, parquet_pruning: bool = True, read_only: bool = False) -> None: ...
    @classmethod
    def from_env(cls, environ: Optional[Mapping[str, str]] = None) -> OpenOptions: ...

class QueryResult:
    @property
    def columns(self) -> tuple[str, ...]: ...
    @property
    def rows(self) -> list[tuple[Any, ...]]: ...

class Database:
    def __init__(self, root: Union[str, PathLike[str]], *, options: Optional[OpenOptions] = None) -> None: ...
    @classmethod
    def from_env(cls, environ: Optional[Mapping[str, str]] = None) -> Database: ...
    @classmethod
    def create(cls, root: Union[str, PathLike[str]], *, bucket: str, region: str,
               prefix: str, tables: Sequence[Mapping[str, Any]],
               seed: Optional[Mapping[str, Iterable[Sequence[Any]]]] = None,
               shards: int = 4, partitions: int = 64, compact_after_files: int = 32,
               max_pending_files: int = 64, write_retry_ms: int = 60000,
               options: Optional[OpenOptions] = None) -> Database: ...
    def query(self, sql: str, params: Sequence[Any] = ()) -> QueryResult: ...
    def execute(self, sql: str, params: Sequence[Any] = ()) -> dict[str, Any]: ...
    def set_parquet_pruning(self, enabled: bool) -> None: ...
    def read_stats(self) -> dict[str, int]: ...
    def settings(self) -> dict[str, Any]: ...
    def compact(self, table: Optional[str] = None, partition: Optional[int] = None) -> list[dict[str, Any]]: ...
    def query_partition_duckdb(self, table: str, routing_key: Any, sql: str,
                              params: Sequence[Any] = (), *, library: str,
                              sqlite_extension: str, threads: int = 2,
                              memory_mb: int = 256) -> QueryResult: ...
    def close(self) -> None: ...
    def __enter__(self) -> Database: ...
    def __exit__(self, *exception: object) -> None: ...
