"""Required real-wire discovery and point operations, not a Mongo parity claim."""

import asyncio
import sys
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime

import pymongo
from bson import Binary, Decimal128, Int64, ObjectId, Regex, Timestamp
from pymongo.errors import BulkWriteError, DuplicateKeyError, OperationFailure


def check_hello(reply):
    assert reply["isWritablePrimary"] is True
    assert reply["maxWireVersion"] == 8
    assert reply["compression"] == []
    assert "logicalSessionTimeoutMinutes" not in reply
    assert "setName" not in reply


def sync_smoke(uri):
    with pymongo.MongoClient(uri, serverSelectionTimeoutMS=3000, socketTimeoutMS=3000, maxPoolSize=3) as client:
        assert client.admin.command("ping")["ok"] == 1
        check_hello(client.admin.command("hello"))
        assert client.server_info()["version"].endswith("-briskdb")
        with ThreadPoolExecutor(max_workers=3) as pool:
            assert all(pool.map(lambda _: client.admin.command("ping")["ok"] == 1, range(12)))
        try:
            client.example.command("aggregate", "items", pipeline=[], cursor={})
        except OperationFailure as error:
            assert error.code == 59
        else:
            raise AssertionError("unimplemented data commands must fail explicitly")
    # A new client proves reconnect after a pool is closed.
    with pymongo.MongoClient(uri, serverSelectionTimeoutMS=3000, socketTimeoutMS=3000) as client:
        assert client.admin.command("ping")["ok"] == 1
    # Offering compression must not cause the driver to compress when the server
    # negotiates none. zlib is available without optional codec dependencies.
    with pymongo.MongoClient(uri, compressors="zlib", serverSelectionTimeoutMS=3000, socketTimeoutMS=3000) as client:
        assert client.admin.command("ping")["ok"] == 1


def document_smoke(uri):
    with pymongo.MongoClient(uri, serverSelectionTimeoutMS=3000, socketTimeoutMS=3000, maxPoolSize=3) as client:
        collection = client.wire_data.items
        assert client.never_written.items.find_one({"_id": "missing"}) is None
        document = {
            "_id": "typed", "integer": Int64(42), "decimal": Decimal128("1.250"),
            "binary": Binary(b"\x00\xff", 128), "when": datetime(2026, 1, 2, 3, 4, 5),
            "stamp": Timestamp(123, 7), "nested": {"values": [None, True, "hello"]},
        }
        assert collection.insert_one(document).inserted_id == "typed"
        actual = collection.find_one({"_id": "typed"})
        assert actual == document
        assert isinstance(actual["integer"], Int64)
        generated = {"value": "generated by PyMongo"}
        result = collection.insert_one(generated)
        assert isinstance(result.inserted_id, ObjectId)
        assert collection.find_one({"_id": result.inserted_id}) == generated
        for identifier in [None, Int64(42), Binary(b"id", 128), {"compound": "id"}]:
            collection.insert_one({"_id": identifier, "value": "typed id"})
            assert collection.find_one({"_id": identifier})["value"] == "typed id"
        try:
            collection.insert_one({"_id": 42.0, "secret": "must-not-leak"})
        except DuplicateKeyError as error:
            assert error.code == 11000
            assert "must-not-leak" not in str(error)
        else:
            raise AssertionError("BSON-equal IDs must raise DuplicateKeyError")
        # Existing engine routing remains authoritative across pooled sockets.
        def round_trip(number):
            item = {"_id": f"parallel-{number}", "number": number}
            collection.insert_one(item)
            return collection.find_one({"_id": item["_id"]}) == item
        with ThreadPoolExecutor(max_workers=3) as pool:
            assert all(pool.map(round_trip, range(12)))
        boundary = {"_id": "near-limit", "value": "x" * (512 * 1024 - 100)}
        collection.insert_one(boundary)
        assert collection.find_one({"_id": "near-limit"}) == boundary
        assert client.other_database.items.find_one({"_id": "typed"}) is None
        for arguments, code in [
            ({"filter": {"$where": "unsupported"}}, 115),
            ({"filter": {"_id": "typed"}, "projection": {"integer": 1}}, 72),
            ({"filter": {"_id": "typed"}, "lsid": {"id": Binary(b"0" * 16, 4)}}, 72),
        ]:
            try:
                client.wire_data.command("find", "items", **arguments)
            except OperationFailure as error:
                assert error.code == code
            else:
                raise AssertionError("unsupported options must fail explicitly")
    with pymongo.MongoClient(uri, serverSelectionTimeoutMS=3000, socketTimeoutMS=3000) as client:
        assert client.wire_data.items.find_one({"_id": "typed"})["decimal"] == Decimal128("1.250")


def batch_smoke(uri):
    with pymongo.MongoClient(uri, serverSelectionTimeoutMS=3000, socketTimeoutMS=20000, maxPoolSize=3) as client:
        for ordered in [True, False]:
            collection = client.wire_batches[f"ordered_{ordered}"]
            documents = [{"_id": identifier, "position": index} for index, identifier in enumerate([1, 1.0, 2, 2.0, 3])]
            try:
                collection.insert_many(documents, ordered=ordered)
            except BulkWriteError as error:
                assert error.details["nInserted"] == (1 if ordered else 3)
                assert [(item["index"], item["code"]) for item in error.details["writeErrors"]] == (
                    [(1, 11000)] if ordered else [(1, 11000), (3, 11000)]
                )
                assert error.details["writeConcernErrors"] == []
            else:
                raise AssertionError("duplicates must report batch indices and partial success")
            assert collection.find_one({"_id": 1}) == documents[0]
            assert (collection.find_one({"_id": 3}) is None) == ordered
        generated = [{"value": "generated"}, {"_id": None}, {"value": "generated again"}]
        result = client.wire_batches.generated.insert_many(generated)
        assert result.inserted_ids == [item["_id"] for item in generated]
        assert result.inserted_ids[1] is None
        assert all(isinstance(result.inserted_ids[index], ObjectId) for index in [0, 2])
        for item in generated:
            assert client.wire_batches.generated.find_one({"_id": item["_id"]}) == item
        # The driver's advertised maxWriteBatchSize split must preserve results.
        documents = [{"_id": number} for number in range(1001)]
        result = client.wire_batches.split.insert_many(documents)
        assert result.inserted_ids == list(range(1001))
        for number in [0, 999, 1000]:
            assert client.wire_batches.split.find_one({"_id": number}) == {"_id": number}
        # Contending connections must not admit BSON-equal duplicate IDs.
        collection = client.wire_batches.concurrent
        collection.insert_one({"_id": "seed"})
        def insert_contended(_):
            try:
                return len(collection.insert_many([{"_id": number} for number in range(20)], ordered=False).inserted_ids)
            except BulkWriteError as error:
                assert all(item["code"] == 11000 for item in error.details["writeErrors"])
                return error.details["nInserted"]
        with ThreadPoolExecutor(max_workers=3) as pool:
            assert sum(pool.map(insert_contended, range(3))) == 20
        # Only direct zero timestamps are server-stamped, never nested values or IDs.
        zero = Timestamp(0, 0)
        documents = [
            {"_id": "first", "stamp": zero, "second": zero, "nested": {"stamp": zero}, "array": [zero]},
            {"_id": "second", "stamp": zero, "nonzero": Timestamp(0, 1)},
            {"_id": zero, "stamp": zero},
        ]
        client.wire_batches.timestamps.insert_many(documents)
        stamps = []
        for document in documents:
            actual = client.wire_batches.timestamps.find_one({"_id": document["_id"]})
            assert actual["stamp"].time > 0
            stamps.append(actual["stamp"])
            assert document["stamp"] == zero
        actual = client.wire_batches.timestamps.find_one({"_id": "first"})
        assert actual["nested"]["stamp"] == actual["array"][0] == zero
        assert actual["second"] != actual["stamp"]
        assert len(set(stamps)) == len(stamps)
        assert client.wire_batches.timestamps.find_one({"_id": "second"})["nonzero"] == Timestamp(0, 1)


def query_smoke(uri):
    with pymongo.MongoClient(uri, serverSelectionTimeoutMS=3000, socketTimeoutMS=3000) as client:
        collection = client.wire_queries.items
        collection.insert_many([
            {"_id": "missing"},
            {"_id": "null", "v": None},
            {"_id": "array", "v": [2, 7, 12], "items": [{"score": 1}, {"score": 5}]},
            {"_id": "number", "v": 7.0, "items": [{"other": 1}, {"score": 2}]},
            {"_id": "string", "v": "Abxc"},
            {"_id": "nested", "v": [[1, 2]], "items": [[{"score": 1}]]},
        ])
        cases = [
            ({"v": None}, ["missing", "null"]),
            ({"v": {"$ne": None}}, ["array", "nested", "number", "string"]),
            ({"v": {"$elemMatch": {"$gte": 5, "$lt": 10}}}, ["array"]),
            ({"v": {"$in": [7]}}, ["array", "number"]),
            ({"v": {"$type": "array"}}, ["array", "nested"]),
            ({"v": {"$regex": "ab.c", "$options": "i"}}, ["string"]),
            ({"items.score": {"$gt": 1}}, ["array", "number"]),
            ({"v.0": [1, 2]}, ["nested"]),
            ({"$or": [{"v": 7}, {"v": "Abxc"}]}, ["array", "number", "string"]),
            ({"$nor": [{"v": {"$exists": True}}]}, ["missing"]),
            ({"_id": {"$eq": "number"}}, ["number"]),
        ]
        for query, expected in cases:
            assert sorted(item["_id"] for item in collection.find(query)) == expected, query
        assert len(list(collection.find())) == 6
        assert [item["_id"] for item in collection.find({"v": {"$ne": None}}).skip(1).limit(2)] == ["number", "string"]
        assert collection.find_one({"v": {"$type": "number"}})["_id"] == "array"
        result = client.wire_queries.command("find", "items", filter={}, batchSize=2, singleBatch=True)
        assert result["cursor"]["id"] == 0
        assert [item["_id"] for item in result["cursor"]["firstBatch"]] == ["missing", "null"]
        for database in [client.wire_queries, client.invalid_query_must_not_create]:
            for query, code in [
                ({"v": {"$not": {}}}, 2),
                ({"$or": [{}, {"v": {"$size": "bad"}}]}, 2),
                ({"v": {"$type": True}}, 14),
                ({"v": {"$type": []}}, 9),
                ({"v": {"$regex": "["}}, 51091),
                ({"v": {"$regex": "x", "$options": "q"}}, 51108),
                ({"v": {"$regex": Regex("x", "i"), "$options": "i"}}, 51075),
                ({"$where": "not executed"}, 115),
            ]:
                try:
                    database.command("find", "items", filter=query)
                except OperationFailure as error:
                    assert error.code == code, (query, error)
                else:
                    raise AssertionError("all branches must validate, even for an absent collection")
        assert client.admin.command("ping")["ok"] == 1


def persisted_smoke(uri):
    with pymongo.MongoClient(uri, serverSelectionTimeoutMS=3000, socketTimeoutMS=3000) as client:
        assert client.wire_data.items.find_one({"_id": "typed"})["decimal"] == Decimal128("1.250")
        assert client.wire_data.items.find_one({"_id": None})["value"] == "typed id"
        assert client.async_data.items.find_one({"_id": "async"})["value"] == "async write"
        assert client.wire_batches.ordered_True.find_one({"_id": 3}) is None
        assert client.wire_batches.ordered_False.find_one({"_id": 3})["position"] == 4
        assert client.wire_batches.split.find_one({"_id": 1000}) == {"_id": 1000}
        assert client.wire_batches.timestamps.find_one({"_id": "first"})["stamp"].time > 0
        assert client.async_data.batches.find_one({"_id": 2}) == {"_id": 2}
        assert sorted(item["_id"] for item in client.wire_queries.items.find({"v": {"$in": [7]}})) == ["array", "number"]


async def async_smoke(uri):
    async with pymongo.AsyncMongoClient(uri, serverSelectionTimeoutMS=3000, socketTimeoutMS=3000, maxPoolSize=3) as client:
        assert (await client.admin.command("ping"))["ok"] == 1
        check_hello(await client.admin.command("hello"))
        replies = await asyncio.gather(*(client.admin.command("ping") for _ in range(12)))
        assert all(reply["ok"] == 1 for reply in replies)
        try:
            await client.example.command("aggregate", "items", pipeline=[], cursor={})
        except OperationFailure as error:
            assert error.code == 59
        else:
            raise AssertionError("unimplemented async commands must fail explicitly")
        collection = client.async_data.items
        assert (await collection.insert_one({"_id": "async", "value": "async write"})).acknowledged
        assert await collection.find_one({"_id": "async"}) == {"_id": "async", "value": "async write"}
        try:
            await collection.insert_one({"_id": "async"})
        except DuplicateKeyError as error:
            assert error.code == 11000
        else:
            raise AssertionError("async duplicate insert must fail")
        try:
            await client.async_data.batches.insert_many([{"_id": 1}, {"_id": 1.0}, {"_id": 2}], ordered=False)
        except BulkWriteError as error:
            assert error.details["nInserted"] == 2
            assert [(item["index"], item["code"]) for item in error.details["writeErrors"]] == [(1, 11000)]
        else:
            raise AssertionError("async unordered batch must report duplicate and continue")
        assert await client.async_data.batches.find_one({"_id": 2}) == {"_id": 2}
        rows = await client.wire_queries.items.find({"items.score": {"$gt": 1}}).to_list()
        assert sorted(item["_id"] for item in rows) == ["array", "number"]


if __name__ == "__main__":
    assert pymongo.version == "4.17.0", "use the pinned real-driver version"
    if len(sys.argv) > 2 and sys.argv[2] == "reopened":
        persisted_smoke(sys.argv[1])
    else:
        sync_smoke(sys.argv[1])
        document_smoke(sys.argv[1])
        batch_smoke(sys.argv[1])
        query_smoke(sys.argv[1])
        asyncio.run(asyncio.wait_for(async_smoke(sys.argv[1]), timeout=20))
    print("PyMongo 4.17.0 discovery, insert batches, exact-ID find, BSON, and rejection passed")
