"""Source-locked legacy physical-ID import, followed by stock driver mutations."""

from pathlib import Path
import math
import sqlite3
import sys

NAMES = ("legacy_integer", "legacy_double", "legacy_string", "legacy_zero")
VALUES = (1, 1.0, "1", -0.0)


def before(database):
    assert set(database.list_collection_names()) == set(NAMES)
    for name, value in zip(NAMES, VALUES):
        collection = database[name]
        assert collection.count_documents({}) == 1
        document = collection.find_one({"_id": value})
        assert document["label"] == "before"
        assert type(document["_id"]) is type(value)
        assert collection.find_one({"_id": True}) is None
    for name in NAMES[:2]:
        assert database[name].find_one({"_id": "1"}) is None
        assert database[name].find_one({"_id": {"$eq": 1}})["label"] == "before"
    assert list(database.legacy_string.find({"$nor": [{"_id": 1}]})) == [{"_id": "1", "label": "before"}]
    assert math.copysign(1, database.legacy_zero.find_one({"_id": 0})["_id"]) == -1


def source(mode, root):
    # Reuse the existing pinned module-hash verification, not an import shim.
    from mongo_operating_client import source_client

    if mode == "seed":
        assert not root.exists(), "requires a new test-owned source"
        client = source_client(root, "sqlite")
        try:
            for name, value in zip(NAMES, VALUES):
                client.app[name].insert_one({"_id": value, "label": "before"})
        finally:
            client.close()
        # Reproduce the upstream legacy fixtures: only the physical key changes
        # to str(_id). JSON payloads/metadata remain generated by locked TinyMongo.
        connection = sqlite3.connect(str(root / "app.sqlite"))
        try:
            for name, key in zip(NAMES, ("1", "1.0", "1", "-0.0")):
                assert connection.execute(f'UPDATE "{name}" SET _id = ?', (key,)).rowcount == 1
            connection.commit()
            assert connection.execute("PRAGMA wal_checkpoint(TRUNCATE)").fetchone()[0] == 0
        finally:
            connection.close()
    client = source_client(root, "sqlite")
    try:
        before(client.app)
    finally:
        client.close()


def wire(mode, uri):
    import pymongo
    from bson import Decimal128
    from pymongo.errors import BulkWriteError, DuplicateKeyError

    assert not any(name == "tinymongo" or name.startswith("tinymongo.") for name in sys.modules)
    with pymongo.MongoClient(uri, maxPoolSize=1, serverMonitoringMode="poll",
                            serverSelectionTimeoutMS=5000, connectTimeoutMS=5000, socketTimeoutMS=5000) as client:
        database = client.app
        if mode == "mutate":
            before(database)
            for name in NAMES[:2]:
                try:
                    database[name].insert_one({"_id": 1, "label": "duplicate"})
                except DuplicateKeyError as error:
                    assert error.code == 11000
                else:
                    raise AssertionError("imported legacy numeric aliases must remain unique")
                assert database[name].count_documents({}) == 1
                assert database[name].find_one({"_id": 1})["label"] == "before"
                try:
                    database[name].insert_many([{"_id": Decimal128("1.00"), "label": "decimal alias"}])
                except BulkWriteError as error:
                    assert error.details["nInserted"] == 0
                    assert [(item["index"], item["code"]) for item in error.details["writeErrors"]] == [(0, 11000)]
                else:
                    raise AssertionError("imported integers/doubles must reject decimal aliases")
            try:
                database.legacy_zero.insert_many([{"_id": 0.0, "label": "zero alias"}])
            except BulkWriteError as error:
                assert error.details["nInserted"] == 0
                assert [(item["index"], item["code"]) for item in error.details["writeErrors"]] == [(0, 11000)]
            else:
                raise AssertionError("imported negative zero must reject positive zero")
            assert database.legacy_string.insert_many([{"_id": 1, "label": "distinct number"}]).inserted_ids == [1]
            assert database.legacy_integer.replace_one({"_id": 1.0}, {"_id": 1, "label": "after"}).modified_count == 1
            collection = database.legacy_double
            collection.insert_one({"_id": 2, "label": "current"})
            assert sorted(row["label"] for row in collection.find({"$or": [{"_id": 1}, {"_id": 2}]})) == ["before", "current"]
            assert collection.replace_one({"_id": 1}, {"_id": 1.0, "label": "updated"}).modified_count == 1
            assert type(collection.find_one({"_id": 1})["_id"]) is float
            assert collection.delete_one({"_id": 1}).deleted_count == 1
        assert database.legacy_integer.find_one({"_id": 1.0}) == {"_id": 1, "label": "after"}
        assert type(database.legacy_integer.find_one({"_id": 1})["_id"]) is int
        assert database.legacy_integer.find_one({"_id": "1"}) is None
        assert database.legacy_integer.find_one({"_id": True}) is None
        assert database.legacy_double.find_one({"_id": 1.0}) is None
        assert list(database.legacy_double.find({})) == [{"_id": 2, "label": "current"}]
        assert list(database.legacy_string.find({"$nor": [{"_id": 1}]})) == [{"_id": "1", "label": "before"}]
        assert database.legacy_string.find_one({"_id": 1}) == {"_id": 1, "label": "distinct number"}
        assert database.legacy_string.count_documents({}) == 2
        assert database.legacy_zero.count_documents({}) == 1
        assert math.copysign(1, database.legacy_zero.find_one({"_id": 0})["_id"]) == -1
        assert database.legacy_zero.find_one({"_id": Decimal128("0.00")})["label"] == "before"


if __name__ == "__main__":
    mode, address = sys.argv[1:]
    if mode in ("seed", "source-check"):
        source(mode, Path(address))
    else:
        assert mode in ("mutate", "reopen")
        wire(mode, address)
    print("Typed-ID import phase passed:", mode)
