"""Required real-wire discovery and point operations, not a Mongo parity claim."""

import asyncio
import sys
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime

import pymongo
from bson import Binary, Decimal128, Int64, ObjectId, Timestamp
from pymongo.errors import DuplicateKeyError, OperationFailure


def check_hello(reply):
    assert reply["isWritablePrimary"] is True
    assert reply["maxWireVersion"] == 8
    assert reply["compression"] == []
    assert "logicalSessionTimeoutMinutes" not in reply
    assert "setName" not in reply


def sync_smoke(uri):
    with pymongo.MongoClient(uri, serverSelectionTimeoutMS=3000, socketTimeoutMS=3000, maxPoolSize=3) as client:
        assert client.admin.command("ping")["ok"] == 1
        check_hello(client.admin.command("hello"))
        assert client.server_info()["version"].endswith("-briskdb")
        with ThreadPoolExecutor(max_workers=3) as pool:
            assert all(pool.map(lambda _: client.admin.command("ping")["ok"] == 1, range(12)))
        try:
            client.example.command("aggregate", "items", pipeline=[], cursor={})
        except OperationFailure as error:
            assert error.code == 59
        else:
            raise AssertionError("unimplemented data commands must fail explicitly")
    # A new client proves reconnect after a pool is closed.
    with pymongo.MongoClient(uri, serverSelectionTimeoutMS=3000, socketTimeoutMS=3000) as client:
        assert client.admin.command("ping")["ok"] == 1
    # Offering compression must not cause the driver to compress when the server
    # negotiates none. zlib is available without optional codec dependencies.
    with pymongo.MongoClient(uri, compressors="zlib", serverSelectionTimeoutMS=3000, socketTimeoutMS=3000) as client:
        assert client.admin.command("ping")["ok"] == 1


def document_smoke(uri):
    with pymongo.MongoClient(uri, serverSelectionTimeoutMS=3000, socketTimeoutMS=3000, maxPoolSize=3) as client:
        collection = client.wire_data.items
        assert client.never_written.items.find_one({"_id": "missing"}) is None
        document = {
            "_id": "typed", "integer": Int64(42), "decimal": Decimal128("1.250"),
            "binary": Binary(b"\x00\xff", 128), "when": datetime(2026, 1, 2, 3, 4, 5),
            "stamp": Timestamp(123, 7), "nested": {"values": [None, True, "hello"]},
        }
        assert collection.insert_one(document).inserted_id == "typed"
        actual = collection.find_one({"_id": "typed"})
        assert actual == document
        assert isinstance(actual["integer"], Int64)
        generated = {"value": "generated by PyMongo"}
        result = collection.insert_one(generated)
        assert isinstance(result.inserted_id, ObjectId)
        assert collection.find_one({"_id": result.inserted_id}) == generated
        for identifier in [None, Int64(42), Binary(b"id", 128), {"compound": "id"}]:
            collection.insert_one({"_id": identifier, "value": "typed id"})
            assert collection.find_one({"_id": identifier})["value"] == "typed id"
        try:
            collection.insert_one({"_id": 42.0, "secret": "must-not-leak"})
        except DuplicateKeyError as error:
            assert error.code == 11000
            assert "must-not-leak" not in str(error)
        else:
            raise AssertionError("BSON-equal IDs must raise DuplicateKeyError")
        # Existing engine routing remains authoritative across pooled sockets.
        def round_trip(number):
            item = {"_id": f"parallel-{number}", "number": number}
            collection.insert_one(item)
            return collection.find_one({"_id": item["_id"]}) == item
        with ThreadPoolExecutor(max_workers=3) as pool:
            assert all(pool.map(round_trip, range(12)))
        boundary = {"_id": "near-limit", "value": "x" * (512 * 1024 - 100)}
        collection.insert_one(boundary)
        assert collection.find_one({"_id": "near-limit"}) == boundary
        assert client.other_database.items.find_one({"_id": "typed"}) is None
        for arguments, code in [
            ({"filter": {"value": "unsupported"}}, 115),
            ({"filter": {"_id": "typed"}, "projection": {"integer": 1}}, 72),
            ({"filter": {"_id": "typed"}, "lsid": {"id": Binary(b"0" * 16, 4)}}, 72),
        ]:
            try:
                client.wire_data.command("find", "items", **arguments)
            except OperationFailure as error:
                assert error.code == code
            else:
                raise AssertionError("unsupported options must fail explicitly")
    with pymongo.MongoClient(uri, serverSelectionTimeoutMS=3000, socketTimeoutMS=3000) as client:
        assert client.wire_data.items.find_one({"_id": "typed"})["decimal"] == Decimal128("1.250")


def persisted_smoke(uri):
    with pymongo.MongoClient(uri, serverSelectionTimeoutMS=3000, socketTimeoutMS=3000) as client:
        assert client.wire_data.items.find_one({"_id": "typed"})["decimal"] == Decimal128("1.250")
        assert client.wire_data.items.find_one({"_id": None})["value"] == "typed id"
        assert client.async_data.items.find_one({"_id": "async"})["value"] == "async write"


async def async_smoke(uri):
    async with pymongo.AsyncMongoClient(uri, serverSelectionTimeoutMS=3000, socketTimeoutMS=3000, maxPoolSize=3) as client:
        assert (await client.admin.command("ping"))["ok"] == 1
        check_hello(await client.admin.command("hello"))
        replies = await asyncio.gather(*(client.admin.command("ping") for _ in range(12)))
        assert all(reply["ok"] == 1 for reply in replies)
        try:
            await client.example.command("aggregate", "items", pipeline=[], cursor={})
        except OperationFailure as error:
            assert error.code == 59
        else:
            raise AssertionError("unimplemented async commands must fail explicitly")
        collection = client.async_data.items
        assert (await collection.insert_one({"_id": "async", "value": "async write"})).acknowledged
        assert await collection.find_one({"_id": "async"}) == {"_id": "async", "value": "async write"}
        try:
            await collection.insert_one({"_id": "async"})
        except DuplicateKeyError as error:
            assert error.code == 11000
        else:
            raise AssertionError("async duplicate insert must fail")


if __name__ == "__main__":
    assert pymongo.version == "4.17.0", "use the pinned real-driver version"
    if len(sys.argv) > 2 and sys.argv[2] == "reopened":
        persisted_smoke(sys.argv[1])
    else:
        sync_smoke(sys.argv[1])
        document_smoke(sys.argv[1])
        asyncio.run(asyncio.wait_for(async_smoke(sys.argv[1]), timeout=20))
    print("PyMongo 4.17.0 discovery, single insert, exact-ID find, BSON, and rejection passed")
